name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ env.DATABASE_URL }}
      BASE_URL: ${{ env.BASE_URL }}
      GOOGLE_CLIENT_ID: ${{ env.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ env.GOOGLE_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ env.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ env.STRIPE_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --fix-lockfile

      - name: Type check with TypeScript
        run: pnpm run type-check

      - name: Run lint
        run: pnpm run lint

      - name: Install node_modules
        run: pnpm install --no-save
