name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "${{ vars.DATABASE_URL }}"
      BASE_URL: "${{ vars.BASE_URL }}"
      GOOGLE_CLIENT_ID: "${{ vars.GOOGLE_CLIENT_ID }}"
      GOOGLE_CLIENT_SECRET: "${{ vars.GOOGLE_CLIENT_SECRET }}"
      NEXTAUTH_SECRET: "${{ vars.NEXTAUTH_SECRET }}"
      NEXTAUTH_URL: "${{ vars.NEXTAUTH_URL }}"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}"
      STRIPE_SECRET_KEY: "${{ vars.STRIPE_SECRET_KEY }}"

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --fix-lockfile

      - name: Type check with TypeScript
        run: pnpm run type-check

      - name: Run lint
        run: pnpm run lint

      - name: Install node_modules
        run: pnpm install --no-save
