name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "https://test.com"

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --fix-lockfile

      - name: Type check with TypeScript
        run: pnpm run type-check

      - name: Run lint
        run: pnpm run lint

      - name: Install node_modules
        run: pnpm install --no-save
