name: Node.js CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://test.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Type Checking
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint
