name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "https://test.com"
      API_URL: "https://foobar.com/bar"
      OPENAI_API_KEY: "foofaaboobaa"
      BASE_URL: "https://test.com"
      GOOGLE_CLIENT_ID: "foobar"
      GOOGLE_CLIENT_SECRET: "foobar"
      NEXTAUTH_SECRET: "superfakesecret"
      NEXTAUTH_URL: "https://test.com"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_bar"
      STRIPE_SECRET_KEY: "sk_test_foo"

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i --fix-lockfile

      - name: Type check with TypeScript
        run: pnpm run type-check

      - name: Run lint
        run: pnpm run lint

      - name: Install node_modules
        run: pnpm install --no-save
